### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by clemperorpenguin** [kierananthonypenrice/PlayVN#2]
Hello! I don't know if I'll use this for sure but I am working on my first lua project as well, which is a VN. Would you mind adding a license? Based on your statement on the forum you wanted to let folks use this for a VN - maybe MIT license would make sense because it allows commercial use.

Cheers,
Sammy

**Comment by kierananthonypenrice** [comment]
Certainly, I am happy to add a license for anyone to use it for commercial use.

To be honest I thought I had, but I'm not very experienced with this kind of thing. I will take a look at the start of the week, I'm a bit busy over the weekend.

Thanks for the interest in the project though, I hope it is helpful to you. I'll let you know when I have added the license.

________________________________
From: Sammy ***@***.***>
Sent: 22 June 2024 03:56
To: kierananthonypenrice/PlayVN ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kierananthonypenrice/PlayVN] License? (Issue #2)


Hello! I don't know if I'll use this for sure but I am working on my first lua project as well, which is a VN. Would you mind adding a license? Based on your statement on the forum you wanted to let folks use this for a VN - maybe MIT license would make sense because it allows commercial use.

Cheers,
Sammy

**Comment by kierananthonypenrice** [comment]
MIT license should be there now.
