### ISSUE TITLE
"Back" button possible?

### ISSUE THREAD

**Issue by tom-uwu** [kierananthonypenrice/PlayVN#3]
I really like this engine, but I am in no way a programmer. The thing I am trying to achieve is to set either the B button or Left on the D-Pad (not really important) as Back (pretty much the opposite of the A button, return to the previous block of text/previous "Line"). I tried to mess around and figure it out somehow, but it turns out I really lack the ability to do that. The game I am trying to make currently doesn't have any inventory, so that would not be necessary, instead I feel like the back button would be more useful. I make use of it quite a bit when reading through VNs, sometimes I skip a part accidentally or click A too soon, and the only alternative now with PlayVN is to restart your save, which is not ideal since I plan to add quite a bit of text. So yeah would that even be possible without major changing of anything? Thanks in advance, other than this I love what you put out, making something comparable from scratch would be next to impossible for someone like me.

**Comment by kierananthonypenrice** [comment]
Hi Tom,

Unfortunately due to the way in which I have made the engine, going 'back' is not really possible.

You see, in order to avoid having to set the background, the characters, etc for every single line of dialogue, I have it save them in between lines. So for example, when you start a scene you set the background for that scene in the first line of dialogue, and you don't set it again until the background needs to change, all you do is set what the dialogue is for each line. Similar things happen with the characters, and the music etc.

Unfortunately this means you cant go back, because if, for example, you went back from the first line of a new scene to the last line of the previous scene, well the background, music etc for that previous scene could have been set hundreds of lines of dialogue earlier, across branching dialogue paths...

So I am sorry, but using my engine going back in such a fashion is impossible without major modification to the way the engine works.

Thank you very much for your interest though, it's nice to know people are looking at it. If you need any additional help with it, please let me know. I am hoping to return to the engine in the new year sometime, to add new cases to my own game and possibly to look at porting the engine to PC, to allow easy porting of games.

Best Regards

Kieran

________________________________
From: tom-uwu ***@***.***>
Sent: 28 November 2024 23:48
To: kierananthonypenrice/PlayVN ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kierananthonypenrice/PlayVN] "Back" button possible? (Issue #3)


I really like this engine, but I am in no way a programmer. The thing I am trying to achieve is to set either the B button or Left on the D-Pad (not really important) as Back (pretty much the opposite of the A button, return to the previous block of text/previous "Line"). I tried to mess around and figure it out somehow, but it turns out I really lack the ability to do that. The game I am trying to make currently doesn't have any inventory, so that would not be necessary, instead I feel like the back button would be more useful. I make use of it quite a bit when reading through VNs, sometimes I skip a part accidentally or click A too soon, and the only alternative now with PlayVN is to restart your save, which is not ideal since I plan to add quite a bit of text. So yeah would that even be possible without major changing of anything? Thanks in advance, other than this I love what you put out, making something comparable from scratch would be next to impossible for someone like me.

**Comment by tom-uwu** [comment]
Thank you so much for the reply! At least now I know and won't waste more time on trying to achieve something that's basically impossible. It makes sense the way you said it. I'll just keep on going without it, it's really no big deal. I'll keep an eye out for any updates, as I mentioned earlier I really like the project, so thank you for making it!
